# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleMapsTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FirebaseDatabase'

  source 'https://github.com/CocoaPods/Specs.git'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for GoogleMapsTest

end
